# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(374, 337)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.choose_ass_file_input = QtWidgets.QLineEdit(self.centralwidget)
        self.choose_ass_file_input.setGeometry(QtCore.QRect(110, 10, 221, 31))
        self.choose_ass_file_input.setObjectName("choose_ass_file_input")
        self.choose_ass_file_text = QtWidgets.QLabel(self.centralwidget)
        self.choose_ass_file_text.setGeometry(QtCore.QRect(10, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Taipei Sans TC Beta")
        font.setPointSize(14)
        self.choose_ass_file_text.setFont(font)
        self.choose_ass_file_text.setObjectName("choose_ass_file_text")
        self.choose_ass_file_button = QtWidgets.QPushButton(self.centralwidget)
        self.choose_ass_file_button.setGeometry(QtCore.QRect(330, 9, 31, 33))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.choose_ass_file_button.setFont(font)
        self.choose_ass_file_button.setObjectName("choose_ass_file_button")
        self.save_path_text = QtWidgets.QLabel(self.centralwidget)
        self.save_path_text.setGeometry(QtCore.QRect(10, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Taipei Sans TC Beta")
        font.setPointSize(14)
        self.save_path_text.setFont(font)
        self.save_path_text.setObjectName("save_path_text")
        self.save_path_input = QtWidgets.QLineEdit(self.centralwidget)
        self.save_path_input.setGeometry(QtCore.QRect(110, 50, 221, 31))
        self.save_path_input.setObjectName("save_path_input")
        self.save_path_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_path_button.setGeometry(QtCore.QRect(330, 50, 31, 33))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.save_path_button.setFont(font)
        self.save_path_button.setObjectName("save_path_button")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(140, 100, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Taipei Sans TC Beta")
        font.setPointSize(14)
        self.start_button.setFont(font)
        self.start_button.setObjectName("start_button")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(60, 160, 256, 161))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "簡體轉繁體中文字幕轉換工具"))
        self.choose_ass_file_text.setText(_translate("MainWindow", "選擇字幕檔"))
        self.choose_ass_file_button.setText(_translate("MainWindow", "..."))
        self.save_path_text.setText(_translate("MainWindow", "儲存路徑"))
        self.save_path_button.setText(_translate("MainWindow", "..."))
        self.start_button.setText(_translate("MainWindow", "開始轉換"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
